version: '3.8'

services:
  backend:
    build:
      context: ./diffusion_model  # Path to your Flask backend directory
    container_name: flask-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build:
      context: ./diffusion_model/front/chatbot  # Path to your React frontend directory
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
